ssh_cfgs:
- Host: hoge
  HostName: hoge_address
  User: foo
  IdentityFile: /home/hoge/.ssh/hoge_rsa
  Port: 22

- Host: fuga
  HostName: fuga_address
  User: bar
  IdentityFile: /home/fuga/.ssh/fuga_rsa
  Port: 22

gpu_db: ./gpu_database.sqlite3
